// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHKF3M73n-I4rpT8GcvFEAypnZpxummQA',
    appId: '1:777747429758:web:8f90296f803f5e835fdb2f',
    messagingSenderId: '777747429758',
    projectId: 'agro-k-c5da2',
    authDomain: 'agro-k-c5da2.firebaseapp.com',
    storageBucket: 'agro-k-c5da2.appspot.com',
    measurementId: 'G-LSFLXC53R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqvV43wWkjrzfDEV7hSzjRUJjOnGRsMWQ',
    appId: '1:777747429758:android:bb3dc2de18f3bbc05fdb2f',
    messagingSenderId: '777747429758',
    projectId: 'agro-k-c5da2',
    storageBucket: 'agro-k-c5da2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdo1JrRH9J9_r-IIyNa41kodqDm583TGU',
    appId: '1:777747429758:ios:24f6be9930609f405fdb2f',
    messagingSenderId: '777747429758',
    projectId: 'agro-k-c5da2',
    storageBucket: 'agro-k-c5da2.appspot.com',
    iosClientId: '777747429758-el8l3kkamenujula46p0vqjkc55upeps.apps.googleusercontent.com',
    iosBundleId: 'com.agrok.plantAnalysis',
  );
}
