// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn-gBCMktZ2UlemEfNlwEowlxl7Ofa5l4',
    appId: '1:176841698268:web:4812f3f51e8ab11da67d19',
    messagingSenderId: '176841698268',
    projectId: 'agro-k-dev',
    authDomain: 'agro-k-dev.firebaseapp.com',
    storageBucket: 'agro-k-dev.appspot.com',
    measurementId: 'G-4SNYKTD9YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0vICOH4wQR-WvBbg2kO37TUCZuBPT6_8',
    appId: '1:176841698268:android:9d6a487583c1d0a7a67d19',
    messagingSenderId: '176841698268',
    projectId: 'agro-k-dev',
    storageBucket: 'agro-k-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEPgMkk9uWjnu7_6wVQ4vCnhWZhtZCbuM',
    appId: '1:176841698268:ios:51efc26f0ce9311aa67d19',
    messagingSenderId: '176841698268',
    projectId: 'agro-k-dev',
    storageBucket: 'agro-k-dev.appspot.com',
    iosClientId: '176841698268-ri6j37s5jhqcrm2bk62mfe3u7jmghjsk.apps.googleusercontent.com',
    iosBundleId: 'com.agrok.plantAnalysisDev',
  );
}
